team_worksheet/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'

  get 'sessions/home'

  get 'sessions/profile'

  get 'sessions/setting'

  get 'users/new'

  get 'team/index'

  get 'team/index'

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json'}

  root 'sessions#profile'
  match ':controller(/:action(/:id))(.:format)', via: [:get, :post]
  root :to => "sessions#login"
  match "signup", :to => "users#new", via: [:get, :post]
  match "login", :to => "sessions#login", via: [:get, :post]
  match "logout", :to => "sessions#logout", via: [:get, :post]
  match "home", :to => "sessions#home", via: [:get, :post]
  match "profile", :to => "sessions#profile", via: [:get, :post]
  match "setting", :to => "sessions#setting", via: [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

team_worksheet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

team_worksheet/app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_many :users
end

team_worksheet/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
    EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
    validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
    validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
    validates :password, :confirmation => true #password_confirmation attr
    validates_length_of :password, :in => 6..20, :on => :create
    before_save :encrypt_password
    after_save :clear_password
    def encrypt_password
      if password.present?
        self.salt = BCrypt::Engine.generate_salt
        self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
      end
    end
    def clear_password
      self.password = nil
    end
    def self.authenticate(username_or_email="", login_password="")
      if  EMAIL_REGEX.match(username_or_email)
        user = User.find_by_email(username_or_email)
      else
        user = User.find_by_username(username_or_email)
      end
      if user && user.match_password(login_password)
        return user
      else
        return false
      end
    end
    def match_password(login_password="")
      encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
    end
end

team_worksheet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protected
  def authenticate_user
    if session[:user_id]
       # set current user object to @current_user object variable
      @current_user = User.find session[:user_id]
      return true
    else
      redirect_to(:controller => 'sessions', :action => 'login')
      return false
    end
  end
  def save_login_state
    if session[:user_id]
      redirect_to(:controller => 'sessions', :action => 'home')
      return false
    else
      return true
    end
  end
end

team_worksheet/app/controllers/graph_controller.rb
class GraphController < ApplicationController
  def.index
  end

  def data
    respond_to do |format|
      format.json {}
    end
  end
end

team_worksheet/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authenticate_user, :only => [:home, :profile, :setting]
  before_filter :save_login_state, :only => [:login, :login_attempt]
  def login
    #Login Form
  end
  def login_attempt
    authorized_user = User.authenticate(params[:username_or_email],params[:login_password])
    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "suh dude, you logged in as #{authorized_user.username}"
      redirect_to(:action => 'home')
    else
      flash[:notice] = "Invalid Username or Password ya goof"
      flash[:color]= "goofed (invalid)"
      render "login"
    end
  end

  def home
    @user = User.new
  end

  def profile
  end

  def setting
  end
  def logout
    session[:user_id] = nil
    redirect_to :action => 'login'
  end
end

team_worksheet/app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end

end

team_worksheet/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:user_id)
    end
end

team_worksheet/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :save_login_state, :only => [:new, :create]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
    else
      flash[:notice] = "Form is invalid"
      flash[:color]= "invalid"
    end
    render "new"
  end
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

team_worksheet/app/helpers/application_helper.rb
module ApplicationHelper
end

team_worksheet/app/helpers/sessions_helper.rb
module SessionsHelper
end

team_worksheet/app/helpers/team_helper.rb
module TeamHelper
end

team_worksheet/app/helpers/teams_helper.rb
module TeamsHelper
end

team_worksheet/app/helpers/users_helper.rb
module UsersHelper
end

team_worksheet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamWorksheet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

team_worksheet/app/views/team/application.html.erb

<h1>Hello, Rails!</h1>

team_worksheet/app/views/team/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Team Worksheet</title>
    <%= stylesheet_link_tag "team" %>
</head>
<body>
<!-- Navigation -->
	    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	        <div class="container">
	            <!-- Brand and toggle get grouped for better mobile display -->
	            <div class="navbar-header">
	                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	                    <span class="sr-only">Toggle navigation</span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                </button>

	                <%= link_to "Team Worksheet", root_url, class: "navbar-brand" %>
	            </div>
	            <!-- Collect the nav links, forms, and other content for toggling -->
	            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	                <ul class="nav navbar-nav">

	                </ul>
	            </div>
	            <!-- /.navbar-collapse -->
	        </div>
	        <!-- /.container -->
	    </nav>

	    <!-- Page Content -->
	    <div class="container">

	    	<div class="row">
		    	<div class="col-lg-12 text-center">
		    	</div>
	    	</div>
	    	<!-- /.row -->
	    </div>
	    <!-- /.container -->
	  <style>body{padding-top:70px;}</style>
	</body>
	</html>

team_worksheet/app/views/users/new.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Team Worksheet</title>
  <%= stylesheet_link_tag "team", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "team", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<%= yield %>
<body>
<!-- Navigation -->
	    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	        <div class="container">
	            <!-- Brand and toggle get grouped for better mobile display -->
	            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                	 <span class="sr-only">Toggle navigation</span>
                	 <span class="icon-bar"></span>
                	 <span class="icon-bar"></span>
                	 <span class="icon-bar"></span>
                </button>
	              <%= link_to "Profile", root_url, class: "navbar-brand" %>
	            </div>
	            <!-- Collect the nav links, forms, and other content for toggling -->
	            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	                <ul class="nav navbar-nav">
                    <li>
                      <%= link_to "Worksheet", sessions_home_url, class: "navbar-brand"%>
                    </li>
                    <li>
                      <%= link_to "Team", profile_url, class: "navbar-brand" %>
                    </li>
                    <% if @current_user %>
                    <li>
                      <%= link_to "Logout", logout_path, method: :post, data: {confirm: "Are you sure you want to do something like that? Just up and LEAVE?"} %>
                    </li>
                    <% else %>
                    <li>
                      <%=link_to "Login", sessions_login_url %>
                    </li>
                    <li>
                      <%= link_to "Register", users_new_url %>
                    </li>
                    <% end %>
	                </ul>
	            </div>
	            <!-- /.navbar-collapse -->
	        </div>
	        <!-- /.container -->
	    </nav>

	    <!-- Page Content -->
      <div class="container">

	    	<div class="row">
          <div class="Sign_Form">
            <h1>Sign Up</h1>
            <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
            <p> Username:</br> <%= f.text_field :username%> </p>
            <p> Email:</br> <%= f.text_field :email%> </p>
            <p> Password:</br> <%= f.password_field :password%></p>
            <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
            <%= f.submit :Signup %>
            <% end %>
            <% if @user.errors.any? %>
            <ul class="Signup_Errors">
              <% for message_error in @user.errors.full_messages %>
              <li>* <%= message_error %></li>
              <% end %>
            </ul>
            <% end %>
    </div>

    		    	<div class="col-lg-12 text-center">
                <%= yield %>
    		    	</div>
    	    	</div>
    	    	<!-- /.row -->
    	    </div>
    	    <!-- /.container -->
	  <style>body{padding-top:70px;}</style>
	</body>
	</html>